name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Install Node (NO pnpm cache here)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) Install pnpm after Node
      - name: Install pnpm
        run: npm i -g pnpm@9

      - name: Verify pnpm
        run: pnpm --version

      # 3) Install workspace deps
      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile=false

      # 4) Type-check API
      - name: Type-check API
        run: pnpm -F @revcover/api exec tsc --noEmit

      # 5) Build UI
      - name: Build UI
        run: pnpm -F @revcover/ui build
